name: flutterfire_sample_app_check
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_app_check: ^0.3.2+9

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
