// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXfO27omE0OKe5QAAkNAX3Nv8DmAu7fU0',
    appId: '1:420702606971:web:11d1ae2542b06e7426b4de',
    messagingSenderId: '420702606971',
    projectId: 'flutterfire-sample-app-check',
    authDomain: 'flutterfire-sample-app-check.firebaseapp.com',
    storageBucket: 'flutterfire-sample-app-check.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzzremx2qCZEjIjYbgOIy3h-_4awBR6Hg',
    appId: '1:420702606971:android:75a39724fb57164d26b4de',
    messagingSenderId: '420702606971',
    projectId: 'flutterfire-sample-app-check',
    storageBucket: 'flutterfire-sample-app-check.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuK-oewu7_n4thUMSPK8s838bUCCHWn88',
    appId: '1:420702606971:ios:8247ea8a9826d5ca26b4de',
    messagingSenderId: '420702606971',
    projectId: 'flutterfire-sample-app-check',
    storageBucket: 'flutterfire-sample-app-check.appspot.com',
    iosClientId: '420702606971-i83k6i7v9pul4jcj2l1mp33ojlp638h1.apps.googleusercontent.com',
    iosBundleId: 'jp.susatthi.flutterfireSampleAppCheck',
  );
}
